<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    $vendorDir . '/react/promise/src/functions_include.php',
    $vendorDir . '/nikic/php-parser/lib/bootstrap.php',
    $vendorDir . '/ircmaxell/password-compat/lib/password.php',
    $vendorDir . '/swiftmailer/swiftmailer/lib/swift_required.php',
    $vendorDir . '/kriswallsmith/assetic/src/functions.php',
);
