<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'Fusonic\\Linq' => array($vendorDir . '/fusonic/linq/src'),
    'Console' => array($vendorDir . '/pear/console_getopt'),
    'Archive_Tar' => array($vendorDir . '/pear/archive_tar'),
    '' => array($vendorDir . '/pear/pear-core-minimal/src'),
);
