<?php

// include_paths.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    $vendorDir . '/pear/pear_exception',
    $vendorDir . '/pear/console_getopt',
    $vendorDir . '/pear/pear-core-minimal/src',
    $vendorDir . '/pear/archive_tar',
);
