name: Composer

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

permissions:
  contents: read

jobs:
  php:
    runs-on: ubuntu-latest

    name: Check vendor changes
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Set up php
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
      with:
        php-version: 8.2
        coverage: none

    - name: Enforce --no-dev
      run: |
        bash -c "[[ \"`cat composer/installed.json | jq .dev`\" == \"false\" ]] || ( echo 'Please only commit after installing with \"composer install --no-dev\"' && exit 1 )"

    - name: Update composer
      run: sudo composer self-update && composer --version

    - name: Delete dependencies
      run: rm -rf ./*/

    - name: Download dependencies
      run: composer install --no-dev

    - name: Remove tests and other untracked files
      run: git clean -X -d -f

    - name: Dump Autoload
      run: composer dump-autoload

    - name: Check vendor changes
      run: |
        bash -c "[[ ! \"`git status --porcelain . ':!composer/installed.json' ':!composer/installed.php' ':!composer/package-versions-deprecated/src/PackageVersions/Versions.php' `\" ]] || ( echo 'Uncommited vendor changes' && git status && git diff && exit 1 )"
